import type { Plugin } from 'vue'
import {
    KlButton,
    KlProgress,
    KlDialog,
    KlCol,
    KlRow,
    KlLayout,
    KlHeader,
    KlMain,
    KlFooter,
    KlAside,
    KlList,
    KlListItem,
    KlListItemMeta,
    KlDatePicker,
    KlBreadCrumb,
    KlBreadCrumbItem,
    KlInput,
    KlForm,
    KlFormItem,
    KlSwitch,
    KlSelect,
    KlOption,
    KlCheckbox,
    KlRadio,
    KlTimeline,
    KlTimelineItem,
    KlCheckboxGroup,
    KlRadioGroup,
    KlAvatar
} from '@kunlun-design/components'

export default [
    KlButton,
    KlProgress,
    KlDialog,
    KlCol,
    KlRow,
    KlLayout,
    KlHeader,
    KlMain,
    KlFooter,
    KlAside,
    KlList,
    KlListItem,
    KlListItemMeta,
    KlDatePicker,
    KlBreadCrumb,
    KlBreadCrumbItem,
    KlInput,
    KlForm,
    KlFormItem,
    KlSwitch,
    KlSelect,
    KlOption,
    KlCheckbox,
    KlRadio,
    KlTimeline,
    KlTimelineItem,
    KlCheckboxGroup,
    KlRadioGroup,
    KlAvatar
] as Plugin[]
